version: '3.8'

services:
  monai-inference:
    image: projectmonai/monai:1.3.2
    container_name: monai_lung_detection
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./data:/opt/monai/data
      - ./models:/opt/monai/models
      - ./scripts:/opt/monai/scripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: >
      bash -c "pip install monai-deploy-app-sdk dicom2nifti SimpleITK ollama langchain highdicom requests 'numpy<2' && 
               tail -f /dev/null"
    working_dir: /opt/monai

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: monai_backend
    ports:
      - "809:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://postgres:password@db:5432/cmms_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: monai_frontend
    ports:
      - "808:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: monai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cmms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  orthanc:
    image: jodogne/orthanc-plugins
    container_name: monai_orthanc
    ports:
      - "8282:8042"
      - "4242:4242"
    environment:
      - ORTHANC_EXPLORER_2_ENABLED=true
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - orthanc_data:/var/lib/orthanc/db

#  llm:
#    image: ollama/ollama:latest
#    container_name: monai_llm
#    runtime: nvidia
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./data/ollama:/root/.ollama
#      - ./data/output:/output:ro
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]

volumes:
  pgdata:
  orthanc_data:
